---

- name: Create user
  hosts: '{{ target }}'
  become: true

  vars_files:
    - ./vars/variables.yml

  tasks:
  
  - name: Create user
    user:
      name: "{{ new_user_name }}"
      password: "{{ new_user_password }}"
      groups:
        - sudo
      state: present
      shell: /bin/bash
      system: no
      createhome: yes