replicaCount: 1

image:
  repository: git.i-sphere.local/isphere-services/main-service-1
  pullPolicy: Always
  tag: latest

imagePullSecrets: [ ]
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: { }
  name: ""

podAnnotations: { }
podLabels: { }

podSecurityContext: { }

securityContext: { }

service:
  type: LoadBalancer
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: { }
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: [ ]

resources:
  requests:
    cpu: 300m
    memory: 384Mi
  limits:
    cpu: 400m
    memory: 512Mi

livenessProbe:
  httpGet:
    path: /2.00/ping.php
    port: http
readinessProbe:
  httpGet:
    path: /2.00/ping.php
    port: http

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

volumes: [ ]

volumeMounts: [ ]

nodeSelector: { }

tolerations: [ ]

affinity: { }
