apiVersion: v1
kind: Service
metadata:
  name: keydb
  namespace: {{.Release.Namespace}}
  labels:
    app.kubernetes.io/name: keydb
  annotations:
    helm.sh/hook: post-install,post-upgrade
spec:
  ports:
    - name: tcp
      protocol: TCP
      port: 6379
      targetPort: amqp

---
apiVersion: v1
kind: Endpoints
metadata:
  name: keydb
  namespace: {{.Release.Namespace}}
  labels:
    app.kubernetes.io/name: keydb
  annotations:
    helm.sh/hook: post-install,post-upgrade
subsets:
  - addresses:
      - ip: 172.16.99.1
    ports:
      - name: tcp
        protocol: TCP
        port: 6379
