apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: {{.Release.Namespace}}
  labels:
    app.kubernetes.io/name: rabbitmq
  annotations:
    helm.sh/hook: post-install,post-upgrade
spec:
  ports:
    - name: amqp
      protocol: TCP
      port: 5672
      targetPort: amqp
    - name: management
      protocol: TCP
      port: 15672
      targetPort: management

---
apiVersion: v1
kind: Endpoints
metadata:
  name: rabbitmq
  namespace: {{.Release.Namespace}}
  labels:
    app.kubernetes.io/name: rabbitmq
  annotations:
    helm.sh/hook: post-install,post-upgrade
subsets:
  - addresses:
      - ip: 172.16.99.1
    ports:
      - name: amqp
        protocol: TCP
        port: 5672
      - name: management
        protocol: TCP
        port: 15672