apiVersion: apps/v1
kind: Deployment
metadata:
 name: {{ include "pg-bouncer.fullname" . }}
 labels:
    {{- include "pg-bouncer.labels" . | nindent 4 }}
spec:
 replicas: {{ .Values.replicaCount }}
 selector:
    matchLabels:
      {{- include "pg-bouncer.selectorLabels" . | nindent 6 }}
 template:
    metadata:
      labels:
        {{- include "pg-bouncer.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: pgbouncer
              containerPort: 6432
              protocol: TCP
          env:
            - name: PGBOUNCER_DATABASES
              value: "{{- range $key, $value := .Values.pgbouncer.databases }}{{ $key }}={{ $value }} {{ end }}"
            - name: PGBOUNCER_AUTH_TYPE
              value: {{ .Values.pgbouncer.auth_type }}
            - name: PGBOUNCER_AUTH_FILE
              value: {{ .Values.pgbouncer.auth_file }}
          volumeMounts:
            - name: pgbouncer-config
              mountPath: /etc/pgbouncer
      volumes:
        - name: pgbouncer-config
          configMap:
            name: {{ include "pg-bouncer.fullname" . }}-config

