apiVersion: v1
kind: Service
metadata:
 name: {{ include "pg-bouncer.fullname" . }}
 labels:
    {{- include "pg-bouncer.labels" . | nindent 4 }}
spec:
 type: {{ .Values.service.type }}
 ports:
    - port: {{ .Values.service.port }}
      targetPort: pgbouncer
      protocol: TCP
      name: pgbouncer
 selector:
    {{- include "pg-bouncer.selectorLabels" . | nindent 4 }}

