apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "chart.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: web
  ports:
    - name: http
      port: {{ .Values.app.service.port }}
      targetPort: http
  type: {{ .Values.service.type }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}-node-worker
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "chart.name" . }}-node-worker
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: daemon
  ports:
    - name: http
      port: {{ .Values.app.service.port }}
      targetPort: http
  type: {{ .Values.service.type }}
