check_types:
  emt_phone:
    enabled: true
    source:
      code: main-service
    schema:
      allOf:
      - $ref: '#/definitions/schema/default'
      - $ref: '#/definitions/schema/phone'
    mutator:
      template:
        records: |
          {{- range .records }}
          - {{ UnsafeField "Name" .Name }}
          {{- end }}
      status_code:
        non_standard: true
        format: json
        property_path: code
        detail_property_path: message
    upstream:
      provider: main-service
      keydb:
        enabled: true
        scope: emt_phone
        ttl: 24h0m0s
        ttl_failed: 30s
      rabbitmq:
        enabled: true
        scope: emt_phone
      tcp:
        template:
          query: |
            GET /2.00/handler.php?{{ QueryArguments
            "auth" (Env "MODULE_MAIN_SERVICE_ACCESS_TOKEN")
            "plugin" "EMTPlugin"
            "checktype" "emt_phone"
            "phone" (trimPrefix "+" .phone)
            }} HTTP/1.1
    produce:
      items:
        properties:
          Name:
            type: string
        type: object
      type: array
