check_types:
  getcontact_phone:
    enabled: true
    source: { code: main-service }
    schema:
      allOf:
        - $ref: "#/definitions/schema/default"
        - $ref: "#/definitions/schema/phone"
    upstream:
      provider: main-service
      keydb: { enabled: true, scope: getcontact_phone, ttl: 24h, ttl_failed: 30s }
      rabbitmq: { enabled: true, scope: getcontact_phone }
      tcp:
        template:
          # language=HTTP
          query: |
            GET /2.00/handler.php?{{ QueryArguments
              "auth" (Env "MODULE_MAIN_SERVICE_ACCESS_TOKEN")
              "plugin" "GetContactAppPlugin"
              "checktype" "getcontact_phone"
              "phone" (trimPrefix "+" .phone)
            }} HTTP/1.1
    mutator:
      template:
        # @formatter:off
        # language=GoTemplate
        records: |
          {{- range .records }}
          - Name: {{ Quote .Name }}
            Avatar: {{ Quote .Avatar }}
            Badge: {{ Quote .Badge }}
            IsUser: {{ Quote .IsUser }}
            TagsCount: {{ .TagsCount }}
            DeletedTagsCount: {{ .DeletedTagsCount}}
          {{- end }}
        # @formatter:on
      status_code: { non_standard: true, format: json, property_path: code, detail_property_path: message }
    produce:
      type: array
      items:
        type: object
        properties:
          Name: { type: string }
          Avatar: { type: string }
          Badge: { type: string }
          IsUser: { type: string }
          TagsCount: { type: number }
          DeletedTagsCount: { type: number }
