check_types:
  pochta_phone:
    enabled: true
    source:
      code: main-service
    schema:
      allOf:
      - $ref: '#/definitions/schema/default'
      - $ref: '#/definitions/schema/phone'
    mutator:
      template:
        records: |
          {{- range .records }}
          - {{ UnsafeField "Phone" .Phone }}
            {{ UnsafeField "Name" .Name }}
            {{ UnsafeField "Address" .Address }}
            {{ UnsafeField "Result" .Result }}
            {{ UnsafeField "ResultCode" .ResultCode }}
            {{ UnsafeField "Index" .Index }}
            {{ UnsafeField "Region" .Region }}
            {{ UnsafeField "City" .City }}
            {{ UnsafeField "Settlement" .Settlement }}
          {{- end }}
      status_code:
        non_standard: true
        format: json
        property_path: code
        detail_property_path: message
    upstream:
      provider: main-service
      keydb:
        enabled: true
        scope: pochta_phone
        ttl: 24h0m0s
        ttl_failed: 30s
      rabbitmq:
        enabled: true
        scope: pochta_phone
      tcp:
        template:
          query: |
            GET /2.00/handler.php?{{ QueryArguments
            "auth" (Env "MODULE_MAIN_SERVICE_ACCESS_TOKEN")
            "plugin" "PochtaPlugin"
            "checktype" "pochta_phone"
            "phone" (trimPrefix "+" .phone)
            }} HTTP/1.1
    produce:
      items:
        properties:
          Address:
            type: string
          City:
            type: string
          Index:
            type: string
          Name:
            type: string
          Phone:
            type: string
          Region:
            type: string
          Result:
            type: string
          ResultCode:
            type: string
          Settlement:
            type: string
        type: object
      type: array
