check_types:
  samsung_email:
    enabled: true
    source: { code: samsung_email }
    schema:
      allOf:
        - $ref: "#/definitions/schema/default"
        - $ref: "#/definitions/schema/email"
    upstream:
      provider: samsung_auth
      keydb: { enabled: true, scope: samsung_email, ttl: 24h, ttl_failed: 30s }
      rabbitmq: { enabled: true, scope: samsung_email }
      tcp:
        template:
          # language=HTTP
          query: |
            POST /search/auth HTTP/1.1
            Content-Type: application/json
            
            {
                "email": {{ Quote .email }}
            }
    mutator:
      template:
        # @formatter:off
        # language=GoTemplate
        records: |
          {{- range .records }}
          - result: {{ Quote .result }}
            result_code: {{ Quote .result_code }}
          {{- end }}
        # @formatter:on
      status_code: { non_standard: true, format: json, property_path: code, detail_property_path: message }
    produce:
      type: array
      items:
        type: object
        properties:
          result: { type: string }
          result_code: { type: string }
