check_types:
  samsung_person:
    enabled: true
    source: { code: samsung_person }
    schema:
      allOf:
        - $ref: "#/definitions/schema/default"
        - type: object
          properties:
            last_name: { type: string }
            first_name: { type: string }
            date: { type: string, format: date }
          required:
            - last_name
            - first_name
            - date
    upstream:
      provider: samsung_auth
      keydb: { enabled: true, scope: samsung_person, ttl: 24h, ttl_failed: 30s }
      rabbitmq: { enabled: true, scope: samsung_person }
      tcp:
        template:
          # language=HTTP
          query: |
            POST /search/person HTTP/1.1
            Content-Type: application/json
            
            {
                "last_name": {{ Quote .last_name }},
                "first_name": {{ Quote .first_name }},
                "birthdate": {{ Quote (AsDateLayout .date "02.01.2006") }}
            }
    mutator:
      template:
        # @formatter:off
        # language=GoTemplate
        records: |
          {{- range .records }}
          - result: {{ Quote .result }}
            result_code: {{ Quote .result_code }}
            emails:
              {{- range .emails }}
              - {{ Quote . }}
              {{- end }}
          {{- end }}
        # @formatter:on
      status_code: { non_standard: true, format: json, property_path: code, detail_property_path: message }
    produce:
      type: array
      items:
        type: object
        properties:
          result: { type: string }
          result_code: { type: string }
          emails:
            type: array
            items:
              type: string
              format: email
