check_types:
  smsc_phone:
    enabled: true
    source: { code: smsc }
    schema:
      allOf:
        - $ref: "#/definitions/schema/default"
        - dependencies:
            type:
              oneOf:
                - allOf:
                    - $ref: "#/definitions/schema/phone"
                    - properties:
                        type: { enum: [init] }
                - allOf:
                    - type: object
                      properties:
                        callback: { type: object, additionalProperties: true }
                      required:
                        - callback
                    - properties:
                        type: { enum: [callback] }
    upstream:
      provider: smsc
      keydb: { enabled: true, scope: smsc_phone, ttl: 24h, ttl_failed: 30s }
      rabbitmq:
        {
          enabled: true,
          scope: smsc_phone,
          async: { enabled: true, scope: smsc_phone__callback },
        }
      tcp:
        template:
          # @formatter:off
          # language=GoTemplate
          query: |
            {{- if eq .type "init" }}
            POST /api/v1/smsc HTTP/1.1
            Content-Type: application/json
            X-Message-ID: {{ .key }}

            {"tel": {{ Quote .phone }}}
            {{- else if eq .type "callback" }}
            POST /callback/smsc HTTP/1.1
            Content-Type: application/json

            {{ ToJSON .callback }}
            {{- end }}
          # @formatter:on
    mutator:
      template:
        # @formatter:off
        # language=GoTemplate
        records: |
          {{- $hlrErrors := `
          "0": "Доступен"
          "1": "Не существует"
          "6": "Не в сети"
          "11": "Нет услуги SMS" 
          "13": "Заблокирован" 
          "21": "Не принимает SMS" 
          "99": "Неизвестная ошибка" 
          "248": "Неизвестный оператор" 
          "249": "Неверный номер" 
          "250": "Ограничен доступ" 
          "251": "Превышен лимит" 
          "252": "Номер запрещен" 
          "253": "Услуга не поддерживается" 
          "255": "Запрос отклонен"
          ` | FromYAML }}
          {{- $regions := `
          "01": "Республика Адыгея (Адыгея)" 
          "02": "Республика Башкортостан" 
          "03": "Республика Бурятия" 
          "04": "Республика Алтай" 
          "05": "Республика Дагестан" 
          "06": "Республика Ингушетия" 
          "07": "Кабардино-Балкарская Республика" 
          "08": "Республика Калмыкия" 
          "09": "Карачаево-Черкесская Республика" 
          "10": "Республика Карелия" 
          "11": "Республика Коми" 
          "12": "Республика Марий Эл" 
          "13": "Республика Мордовия" 
          "14": "Республика Саха (Якутия)" 
          "15": "Республика Северная Осетия - Алания" 
          "16": "Республика Татарстан" 
          "17": "Республика Тыва" 
          "18": "Удмуртская Республика" 
          "19": "Республика Хакасия" 
          "20": "Чеченская Республика" 
          "21": "Чувашская Республика" 
          "22": "Алтайский край" 
          "23": "Краснодарский край" 
          "24": "Красноярский край" 
          "25": "Приморский край" 
          "26": "Ставропольский край" 
          "27": "Хабаровский край" 
          "28": "Амурская область" 
          "29": "Архангельская область" 
          "30": "Астраханская область" 
          "31": "Белгородская область" 
          "32": "Брянская область" 
          "33": "Владимирская область" 
          "34": "Волгоградская область" 
          "35": "Вологодская область" 
          "36": "Воронежская область" 
          "37": "Ивановская область" 
          "38": "Иркутская область" 
          "39": "Калининградская область" 
          "40": "Калужская область" 
          "41": "Камчатская область" 
          "42": "Кемеровская область" 
          "43": "Кировская область" 
          "44": "Костромская область" 
          "45": "Курганская область" 
          "46": "Курская область" 
          "47": "Ленинградская область" 
          "48": "Липецкая область" 
          "49": "Магаданская область" 
          "50": "Московская область" 
          "51": "Мурманская область" 
          "52": "Нижегородская область" 
          "53": "Новгородская область" 
          "54": "Новосибирская область" 
          "55": "Омская область" 
          "56": "Оренбургская область" 
          "57": "Орловская область" 
          "58": "Пензенская область" 
          "59": "Пермский край" 
          "60": "Псковская область" 
          "61": "Ростовская область" 
          "62": "Рязанская область" 
          "63": "Самарская область" 
          "64": "Саратовская область" 
          "65": "Сахалинская область" 
          "66": "Свердловская область" 
          "67": "Смоленская область" 
          "68": "Тамбовская область" 
          "69": "Тверская область" 
          "70": "Томская область" 
          "71": "Тульская область" 
          "72": "Тюменская область" 
          "73": "Ульяновская область" 
          "74": "Челябинская область" 
          "75": "Читинская область" 
          "76": "Ярославская область" 
          "77": "Москва" 
          "78": "Санкт - Петербург" 
          "79": "Еврейская автономная область" 
          "80": "Агинский Бурятский автономный округ" 
          "81": "Коми-Пермяцкий автономный округ" 
          "82": "Корякский автономный округ" 
          "83": "Ненецкий автономный округ" 
          "84": "Таймырский (Долгано-Ненецкий) автономный округ" 
          "85": "Усть-Ордынский Бурятский автономный округ" 
          "86": "Ханты-Мансийский автономный округ (Югра)" 
          "87": "Чукотский автономный округ" 
          "88": "Эвенкийский автономный округ" 
          "89": "Ямало-Ненецкий автономный округ" 
          "99": "Иные территории Байконур" 
          ` | FromYAML }}
          {{ range .data }}
            {{- $statusInt := atoi .status }}
          - PhoneNumber: {{ Quote .phone }}
            {{- if gt $statusInt 0 }}
            {{-   if eq $statusInt 1 }}
            HLRStatus:        !!string {{ .statusInt }}
            HLRStatusText:    Доступен
            {{-   else }}
            {{-     if not (eq .err "") }}
            HLRStatus: !!string -{{ .err }}
            {{-       $hlrError := (GetSafe $hlrErrors .err) }}
            {{-       if not (eq $hlrError "") }}
            HLRStatusText: {{ Quote $hlrError }}
            {{-       else }}
            HLRStatusText: Ошибка обработки запроса
            {{-       end }}
            {{-     else }}
            HLRStatus:        !!string -99
            HLRStatusText:    Услуга не поддерживается
            {{-     end }}
            {{-   end }}
            {{- end }}
            Operator:     {{ Quote .net }}
            Country:      {{ Quote .cn }}
            IMSI:         {{ Quote .imsi }}
            {{- if not (eq .msc "") }}
            MSC: {{ Quote (print (StringsSubstring .msc 0 11) "xxxxx") }}
            {{- else }}
            MSC: ""
            {{- end }}
          {{- end }}
        # @formatter:on
    produce:
      type: array
      items:
        type: object
        properties:
          PhoneNumber: { type: string }
          HLRStatus: { type: string }
          HLRStatusText: { type: string }
          Operator: { type: string }
          Country: { type: string }
          IMSI: { type: string }
          MSC: { type: string }
