check_types:
  vk_email:
    enabled: true
    source: { code: hasura }
    schema:
      allOf:
        - $ref: "#/definitions/schema/default"
        - $ref: "#/definitions/schema/email"
    upstream:
      provider: hasura
      keydb: { enabled: true, scope: vk_email, ttl: 24h, ttl_failed: 30s }
      rabbitmq: { enabled: true, scope: vk_email }
      graphql:
        # language=GraphQL
        query: |
          query($email: String!){
              vk_emails(where: {email: {_eq: $email}}){
                  vk_id
              }
          }
        # @formatter:on
    mutator:
      template:
        # @formatter:off
        # language=GoTemplate
        records: |
          {{- range (Root . "vk_emails") }}
          - url: https://vk.com/id{{ Print .vk_id }}
          {{- end }}
        # @formatter:on
    produce:
      type: array
      items:
        type: object
        properties:
          url: { type: string, format: url }
