check_types:
  yoomoney_email:
    enabled: true
    source: {code: yoomoney}
    schema:
      allOf:
        - $ref: "#/definitions/schema/default"
        - type: object
          properties:
            email: {type: string, format: email}
          required:
            - email
    upstream:
      provider: yoomoney
      keydb: {enabled: true, scope: yoomoney_email, ttl: 24h, ttl_failed: 30s}
      rabbitmq: {enabled: true, scope: yoomoney_email}
      tcp:
        template:
          # language=HTTP
          query: |
            POST / HTTP/1.1
            Content-Type: application/json 

            {
                "email": {{ .email | Quote }}
            }
    mutator:
      template:
        # @formatter:off
        # language=GoTemplate
        records: |
          {{- range .data }}
          - account: {{ Quote .accountInfo.account }}
            email: {{ Quote .accountInfo.email }}
            resolveType: {{ Quote .accountInfo.resolveType }}
            identification: {{ Quote .accountInfo.identification }}
          {{- end }}
        # @formatter:off
    produce:
      type: array
      items:
        type: object
        properties:
          account: {type: string}
          email: {type: string}
          resolveType: {type: string}
          identification: {type: string}
