apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chart.name" . }}-php-fpm-configmap
  labels:
    {{- include "chart.labels" . | nindent 4 }}
data:
  APP_ENV: "dev"

  DATABASE_SERVER: "172.16.99.3"
  DATABASE_NAME: "isphere"
  DATABASE_CONNECT_TIMEOUT: "5"
  DATABASE_READ_TIMEOUT: "60"

  DATABASE_STAT_SERVER: "172.16.99.3"
  DATABASE_STAT_NAME: "isphere"
  DATABASE_STAT_CONNECT_TIMEOUT: "5"
  DATABASE_STAT_READ_TIMEOUT: "60"

  KEYDB_SERVER_0: "keydb.keydb.svc.cluster.local"
  KEYDB_SERVER_1: "keydb.keydb.svc.cluster.local"
  KEYDB_SERVER_2: "keydb.keydb.svc.cluster.local"

  KEYDB_CONNECT_TIMEOUT: "1"
  KEYDB_READ_TIMEOUT: "1"

  RABBITMQ_HOST: "i-sphere.rabbitmq.svc.cluster.local"
  RABBITMQ_PORT: "5672"
  RABBITMQ_VHOST: "/"

  TEXT_CAPTCHA_URLS: "http://textcaptcha.default.svc.cluster.local"

  JAEGER_HOST: "jaeger-agent.jaeger.svc.cluster.local"
  JAEGER_PORT: "6831"
