apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "chart.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: web
  ports:
    - name: dns
      port: {{ .Values.app.service.port }}
      targetPort: dns
      protocol: UDP
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
  type: {{ .Values.service.type }}
