version: '3.8'

services:
  huawei-api:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: huawei_web_api_dev
    ports:
      - "8001:8001"
    volumes:
      - .:/app
      - /app/__pycache__
    working_dir: /app
    env_file:
      - .env.dev
    environment:
      - MODE=development
      - DEBUG=true
      - PORT=8001
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8001", "--reload"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  redis:
    image: redis:7.2-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  redis_data:
