apiVersion: v1
kind: Service
metadata:
  name: redmine
  labels:
    app.kubernetes.io/name: redmine
  annotations:
    helm.sh/hook: post-install,post-upgrade
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
---
apiVersion: v1
kind: Endpoints
metadata:
  name: redmine
  labels:
    app.kubernetes.io/name: redmine
  annotations:
    helm.sh/hook: post-install,post-upgrade
subsets:
  - addresses:
      - ip: 172.16.97.0
    ports:
      - port: 8000
