imageCredentials:
  enabled: false
  registry: ""
  username: ""
  password: ""

nameOverride: ""
fullNameOverride: ""

DOCKER: "${DOCKER}"

securityContext:
  capabilities:
    drop: [ FOWNER,KILL,MKNOD,SETGID,SETUID ]

podAnnotations: { }

podSecurityContext: { }

nodeSelector: { }

tolerations: [ ]

serviceAccount:
  create: true
  annotations: { }
  createRole: true
  affinity: { }

app:
  replicaCount: 1

  image:
    repository: "${CI_REGISTRY_IMAGE}"
    pullPolicy: Always
    tag: "${DRONE_BRANCH}"

  resources:
    limits:
      cpu: 50m
      memory: 80Mi
    requests:
      cpu: 20m
      memory: 64Mi
