parameters:

services:
  _defaults:
    autowire: true
    autoconfigure: true
    bind:
      string $kernelCacheDir: '%kernel.cache_dir%'

  App\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Kernel.php'
