apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chart.fullname" . }}-http-serve
  labels:
    {{- include "chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  replicas: {{ .Values.http_serve.replicaCount }}
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "chart.name" . }}-http-serve
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: web
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        app.kubernetes.io/name: {{ include "chart.name" . }}-http-serve
        app.kubernetes.io/instance: {{ .Release.Name }}
        date: "{{ now | unixEpoch }}"
        app.kubernetes.io/component: web
    spec:
      containers:
        - name: app
          image: "{{ .Values.http_serve.image.repository }}:{{ .Values.http_serve.image.tag }}"
          imagePullPolicy: {{ .Values.http_serve.image.pullPolicy }}
          ports:
            - name: ssh
              containerPort: 22
          command: [ 'bin/console' ]
          envFrom:
            - configMapRef:
                name: {{ include "chart.name" . }}-configmap-http-serve
          env:
            - name: ADDR
              value: ":22"
          resources:
            {{- toYaml .Values.http_serve.resources | nindent 12 }}
      serviceAccountName: {{ include "chart.serviceAccountName" . }}
      imagePullSecrets:
        - name: {{ include "chart.name" . }}-registry
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- with .Values.serviceAccount.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
