apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}-http-serve
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "chart.name" . }}-http-serve
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: web
  ports:
    - name: ssh
      port: 22
      targetPort: ssh
  type: {{ .Values.service.type }}
