{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "k8s-sentry.serviceAccountName" . }}
  labels:
    {{- include "k8s-sentry.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "k8s-sentry.serviceAccountName" . }}-r
rules:
  - apiGroups: [ "" ]
    resources: [ "pods", "services", "events" ]
    verbs: [ "get", "list", "watch" ]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "k8s-sentry.serviceAccountName" . }}-cr
rules:
  - apiGroups: [ "" ]
    resources: [ "pods", "services", "events" ]
    verbs: [ "get", "list", "watch" ]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "k8s-sentry.serviceAccountName" . }}-rb
subjects:
  - kind: ServiceAccount
    name: {{ include "k8s-sentry.serviceAccountName" . }}
roleRef:
  kind: Role
  name: {{ include "k8s-sentry.serviceAccountName" . }}-r
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "k8s-sentry.serviceAccountName" . }}-crb
subjects:
  - kind: ServiceAccount
    name: {{ include "k8s-sentry.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "k8s-sentry.serviceAccountName" . }}-cr
  apiGroup: rbac.authorization.k8s.io
{{- end }}
