name: linter
kind: pipeline
type: kubernetes
pull: if-not-exists
load: none

steps:
- name: yapf-run
  image: python:latest
  volumes:
    - name: yapf-cache
      path: /drone/src/
  commands:
    - git checkout -b $DRONE_SOURCE_BRANCH
    - pip install -qq yapf
    - yapf -r -i src/ *.py
  when:
    event:
      - pull_request
    branch:
      - master
      - dev

- name: yapf-check
  image: python:latest
  depends_on:
    - yapf-run
  volumes:
    - name: yapf-cache
      path: /drone/src/
  commands:
    - git status
    - |
      if [ $(git status --porcelain | wc -l) -eq "0" ]; then 
        echo "No changes detected. Ok"; 
      else 
        echo "Changes detected. Refactor your code and run again"
        exit 1; 
      fi
  when:
    event:
      - pull_request
    branch:
      - master
      - dev

- name: yapf-push
  image: python:latest
  depends_on:
    - yapf-run
  volumes:
    - name: yapf-cache
      path: /drone/src/
  commands:
    - git status
    - |
      if [ $(git status --porcelain | wc -l) != "0" ]; then 
        git commit -am "refactor: yapf autofixes"
        git push --set-upstream origin $DRONE_SOURCE_BRANCH
      else
        echo "Nothing to commit. Ok"
      fi
  when:
    event:
      - pull_request
    branch:
      - master
      - dev

- name: auto-pr
  image: ubuntu:latest
  commands:
    - apt-get update
    - apt-get -qq -y install curl jq
    - REPO_PR_URL_GET=`echo https://git.i-sphere.ru/api/v1/repos/$DRONE_REPO/pulls?state=open\&access_token=$GIT_TOKEN`
    - REPO_PR_URL_CREATE=`echo https://git.i-sphere.ru/api/v1/repos/$DRONE_REPO/pulls?access_token=$GIT_TOKEN`
    - PR_DEV=`curl -s $REPO_PR_URL_GET | jq -r '.[].base.label'`
    - | 
      if [ "$PR_DEV" != "master" ]; then
        curl -X 'POST' `echo $REPO_PR_URL_CREATE` \
        -H 'Content-Type: application/json' \
        -d '{"assignees":["kovinevmv","ar"],"base":"'`echo $DRONE_REPO_BRANCH`'","head":"dev","title":"dev to '`echo $DRONE_REPO_BRANCH`'"}'
      else
        echo "PR already exists."
      fi
  environment:
    GIT_TOKEN:
      from_secret: GIT_TOKEN
  when:
    event:
      - push
    branch:
      - dev

- name: unit-tests
  image: python:latest
  commands:
    - pip install -r requirements.txt
    - python -m unittest discover -s tests/
  environment:
    MONGO_SERVER:
      from_secret: MONGO_SERVER
    MONGO_PORT:
      from_secret: MONGO_PORT
    MONGO_DB:
      from_secret: MONGO_DB
    MONGO_COLLECTION:
      from_secret: MONGO_COLLECTION
  when:
    event:
      - pull_request
    branch:
      - master
      - dev

volumes:
- name: yapf-cache
  temp: {}

trigger:
  event:
    - pull_request
    - push
  branch:
    - master
    - dev