nodeSelector:
  "kubernetes.io/hostname": msk-worker-91

tolerations:
  - key: "qansylli"
    operator: Equal
    value: "true"
    effect: NoExecute

clickhouse:
  env:
    CLICKHOUSE_ADMIN_USER: analytics
    CLICKHOUSE_HTTP_PORT: 8123
    CLICKHOUSE_INTERSERVER_HTTP_PORT: 9009
    CLICKHOUSE_MYSQL_PORT: 9004
    CLICKHOUSE_POSTGRESQL_PORT: 9005
    CLICKHOUSE_TCP_PORT: 9000
  secrets:
    CLICKHOUSE_ADMIN_PASSWORD: analytics
