{{- if eq .Values.kind "cronjob" }}
apiVersion: batch/v1
kind: CronJob

metadata:
  name: {{ .Release.Name  }}
  labels:
    {{- include "sources.labels" . | nindent 4 }}
    app: {{ .Release.Name  }}
spec:
  schedule: "{{ .Values.schedule }}"
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "sources.selectorLabels" . | nindent 6 }}
  jobTemplate:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "sources.selectorLabels" . | nindent 8 }}
        app:  {{ .Release.Name  }}
    template:
      spec:
        {{- with .Values.imagePullSecrets }}
        imagePullSecrets:
          {{- toYaml . | nindent 8 }}
        {{- end }}
          containers:
          - name:  {{ .Release.Name }}
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default "latest" }}"
            imagePullPolicy: {{ .Values.image.pullPolicy | default "IfNotPresent" }}
            restartPolicy: OnFailure
            ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP

              {{- with .Values.livenessProbe }}
              livenessProbe:
              {{- toYaml . | nindent 12 }}
              {{- end }}
              {{- with .Values.readinessProbe }}
              readinessProbe:
              {{- toYaml . | nindent 12 }}
          {{- end }}

            volumeMounts:
            - mountPath: /etc/localtime
              name: tz-config
              subPath: Moscow
            {{- with .Values.resources }}
            resources:
              {{- toYaml . | nindent 12 }}
            {{- end }}
          
          {{- with .Values.command }}
          command:
            {{- toYaml . | nindent 12 }}
         {{- end }}
          {{- with .Values.args }}
          args:
            {{- toYaml . | nindent 12 }}
         {{- end }}
          {{- with .Values.env }}
          env:
            {{- toYaml . | nindent 12 }}
         {{- end }}
          {{- with .Values.envFrom }}
          envFrom:
            {{- toYaml . | nindent 12 }}
         {{- end }}

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      volumes:
      - configMap:
          defaultMode: 420
          name: tz
        name: tz-config
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}