imageCredentials:
  enabled: false
  registry: ""
  username: ""
  password: ""

nameOverride: ""
fullNameOverride: ""

DOCKER: "${DOCKER}"

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  tlsEnabled: false

securityContext:
  capabilities:
    drop:
      - FOWNER
      - KILL
      - MKNOD
      - SETGID
      - SETUID

podAnnotations: {}

podSecurityContext: {}

nodeSelector: {}

tolerations: []

serviceAccount:
  create: true
  annotations: {}
  createRole: true
  affinity: {}

persistence:
  enabled: false

app:
  replicaCount: 1

  service:
    port: 80

  image:
    repository: "${CI_REGISTRY_IMAGE}"
    pullPolicy: Always
    tag: "${DRONE_BRANCH}"

  resources:
    limits:
      cpu: 200m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi

  env:
    APP_ENV: "${APP_ENV}"
    HASURA_ENDPOINT: "${HASURA_ENDPOINT}"
    HASURA_ADMIN_SECRET: "${HASURA_ADMIN_SECRET}"
