# legal template
"Наименование": ~
"Место нахождения и адрес юридического лица": ~
"Сведения о регистрации": ~
"Сведения о регистрирующем органе по месту нахождения юридического лица": ~
"Сведения о лице, имеющем право без доверенности действовать от имени юридического лица": ~
"Сведения об уставном капитале / складочном капитале / уставном фонде / паевом фонде": ~
"Сведения об участниках / учредителях юридического лица":
  "{number}": ~
"Сведения об учете в налоговом органе": ~
"Сведения о регистрации в качестве страхователя по обязательному пенсионному страхованию": ~
"Сведения о регистрации в качестве страхователя по обязательному социальному страхованию": ~
"Сведения о видах экономической деятельности по Общероссийскому классификатору видов экономической деятельности":
  "Сведения об основном виде деятельности":
    "{number}": ~
  "Сведения о дополнительных видах деятельности":
    "{number}": ~
"Сведения о записях, внесенных в Единый государственный реестр юридических лиц":
  "{number}":
    "Сведения о документах, представленных при внесении записи в ЕГРЮЛ": ~
    "Сведения о свидетельстве, подтверждающем факт внесения записи в ЕГРЮЛ": ~
    "Сведения о статусе записи": ~
# extra sections for individual entrepreneurs
"Фамилия, имя, отчество (при наличии) индивидуального предпринимателя": ~
"Сведения о гражданстве": ~
"Сведения о регистрации индивидуального предпринимателя": ~
"Сведения о регистрирующем органе по месту жительства индивидуального предпринимателя": ~
"Сведения о записях, внесенных в ЕГРИП":
  "{number}":
    "Сведения о документах, представленных при внесении записи в ЕГРИП": ~
    "Сведения о свидетельстве, подтверждающем факт внесения записи в ЕГРИП": ~
