version: '3.8'

services:
  xiaomi-aggregator:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: xiaomi_aggregator_api
    ports:
      - "8005:8005"
    env_file:
      - .env
    environment:
      - MODE=production
      - PORT=8005
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8005/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  redis:
    image: redis:7.2-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  redis_data:
