apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-exporter
  namespace: metrics
spec:
  selector:
    matchLabels:
      app: mongodb-exporter
  template:
    metadata:
      labels:
        app: mongodb-exporter
    spec:
      containers:
        - name: mongodb-exporter
          image: percona/mongodb_exporter:0.40.0
          imagePullPolicy: IfNotPresent
          command:
            - /mongodb_exporter
            - --collector.diagnosticdata
            - --collector.replicasetstatus
            - --collector.dbstats
            - --collector.dbstatsfreestorage
            - --collector.topmetrics
            - --collector.currentopmetrics
            - --collector.indexstats
            - --collector.collstats
            - --collector.profile
          env:
            - name: MONGODB_URI
              value: "mongodb://172.16.99.1:27017"
            - name: MONGODB_USER
              valueFrom:
                secretKeyRef:
                  name: settings-kube
                  key: MONGO_ADMIN
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: settings-kube
                  key: MONGO_PASSWORD
          ports:
            - name: http
              containerPort: 9216
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-exporter
  namespace: metrics
spec:
  type: ClusterIP
  selector:
    app: mongodb-exporter
  ports:
    - name: http
      protocol: TCP
      port: 9216
      targetPort: http
