apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-exporter
  namespace: metrics
spec:
  selector:
    matchLabels:
      app: redis-exporter
  template:
    metadata:
      labels:
        app: redis-exporter
    spec:
      containers:
        - name: redis-exporter
          image: oliver006/redis_exporter
          imagePullPolicy: IfNotPresent
          env:
            - name: REDIS_ADDR
              valueFrom:
                secretKeyRef:
                  name: settings-kube
                  key: KEYDB_HOST
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: settings-kube
                  key: KEYDB_PASSWORD
          ports:
            - name: http
              containerPort: 9121
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

---
apiVersion: v1
kind: Service
metadata:
  name: redis-exporter
  namespace: metrics
spec:
  type: LoadBalancer
  selector:
    app: redis-exporter
  ports:
    - name: http
      protocol: TCP
      port: 9121
      targetPort: http
