imageCredentials:
  enabled: false
  registry: ""
  username: ""
  password: ""

nameOverride: ""
fullNameOverride: ""

DOCKER: "${DOCKER}"

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  tlsEnabled: false

securityContext:
  capabilities:
    drop:
      - FOWNER
      - KILL
      - MKNOD
      - SETGID
      - SETUID

podAnnotations: {}

podSecurityContext: {}

nodeSelector: {}

tolerations:
  - key: prod
    operator: Equal
    value: "yes"
    effect: NoSchedule

serviceAccount:
  create: true
  annotations: {}
  createRole: true
  affinity: {}

persistence:
  enabled: false

app:
  replicaCount: 3

  service:
    port: 80

  image:
    repository: "${CI_REGISTRY_IMAGE}"
    pullPolicy: Always
    tag: "${DRONE_BRANCH}"

  resources:
    limits:
      cpu: 200m
      memory: 64Mi
    requests:
      cpu: 100m
      memory: 32Mi

  env:
    ADDR: "${ADDR}"
    APP_DEBUG: "${APP_DEBUG}"
    SHODAN_HOST: "${SHODAN_HOST}"
    SHODAN_TOKEN: "${SHODAN_TOKEN}"
    SENTRY_DSN: "${SENTRY_DSN}"
