replicaCount: 3
image:
  repository: git.i-sphere.local/proxphere/tor-proxy
  pullPolicy: Always
  tag: latest
imagePullSecrets: [ ]
nameOverride: ""
fullnameOverride: ""
serviceAccount:
  create: true
  automount: true
  annotations: { }
  name: ""
podAnnotations: { }
podLabels: { }
podSecurityContext: { }
securityContext: { }
service:
  type: LoadBalancer
  port: 8080
ingress:
  enabled: false
resources: { }
limits:
  cpu: 400m
  memory: 384Mi
requests:
  cpu: 200m
  memory: 256Mi
x-probe: &probe
  failureThreshold: 30
  periodSeconds: 10
  timeoutSeconds: 30
  httpGet:
    path: /health
    port: 8080
startupProbe:
  <<: *probe
livenessProbe:
  <<: *probe
readinessProbe:
  <<: *probe
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80
volumes: [ ]
volumeMounts: [ ]
nodeSelector: { }
tolerations:
  - key: foreign
    operator: Equal
    value: "true"
    effect: NoExecute
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: k8s.i-sphere.ru/rkn-zone
              operator: In
              values:
                - foreign
            - key: kubernetes.io/hostname
              operator: In
              values:
                - pl-worker-01
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        preference:
          matchExpressions:
            - key: k8s.i-sphere.ru/rkn-zone
              operator: In
              values:
                - foreign
            - key: kubernetes.io/hostname
              operator: In
              values:
                - kz-worker-01
ru:
  replicaCount: 3
