imageCredentials:
  enabled: false
  registry: ""
  username: ""
  password: ""

nameOverride: ""
fullNameOverride: ""

DOCKER: "${DOCKER}"

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  tlsEnabled: false

securityContext:
  capabilities:
    drop:
      - FOWNER
      - KILL
      - MKNOD
      - SETGID
      - SETUID

podAnnotations: {}

podSecurityContext: {}

nodeSelector: {}

tolerations: []

serviceAccount:
  create: true
  annotations: {}
  createRole: true
  affinity: {}

persistence:
  enabled: false

x-env: &env
  LISTEN_ADDRESS: "${LISTEN_ADDRESS}"
  CLICKHOUSE_HOST: "${CLICKHOUSE_HOST}"
  CLICKHOUSE_USERNAME: "${CLICKHOUSE_USERNAME}"
  CLICKHOUSE_PASSWORD: "${CLICKHOUSE_PASSWORD}"
  CLICKHOUSE_DATABASE: "${CLICKHOUSE_DATABASE}"

metrics:
  replicaCount: 1
  service:
    port: 80
  image:
    repository: "${CI_REGISTRY_IMAGE}"
    pullPolicy: Always
    tag: "${DRONE_BRANCH}"
  resources:
    limits:
      cpu: 400m
      memory: 128Mi
    requests:
      cpu: 200m
      memory: 64Mi
  env:
    <<: *env
