kind: StatefulSet
#StatefulSet

replicaCount: 3

image:
  repository: git.i-sphere.ru/avito/avito-web-api
  pullPolicy: Always
  # Overrides the image tag whose default is the latest.
  tag: "latest"





resources: {}


env:
- name: MONGO_COLLECTION
  value: avito
- name: KEYDB_QUEUE
  value: avito

affinity: {}



service:
  enabled: true
  type: ClusterIP
  port: 80

imagePullSecrets:
- name: docker-registry
nameOverride: ""
fullnameOverride: ""

nodeSelector: {}

tolerations:
- effect: NoSchedule
  key: prod
  operator: Equal
  value: "yes"

envFrom:
- secretRef:
    name: settings-kube
