apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: daemons
  annotations:
    helm.sh/hook: post-install,post-upgrade
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "chart.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      date: "{{ now | unixEpoch }}"
      app.kubernetes.io/component: daemons
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        app.kubernetes.io/name: {{ include "chart.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        date: "{{ now | unixEpoch }}"
        app.kubernetes.io/component: daemons
    spec:
      restartPolicy: {{ .Values.app.restartPolicy }}
      containers:
        - name: proxy-check
          image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.tag }}"
          imagePullPolicy: {{ .Values.app.image.pullPolicy }}
          envFrom:
            - secretRef:
                name: {{ include "chart.name" . }}-secrets
          resources:
            {{- toYaml .Values.app.resources | nindent 12 }}
          command:
            - sh
            - -exc
            - |
              while true; do
                python proxy_check.py
                sleep 60
              done
      serviceAccountName: {{ include "chart.serviceAccountName" . }}
      imagePullSecrets:
        - name: {{ include "chart.name" . }}-registry
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- with .Values.serviceAccount.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
