kind: pipeline
name: default
type: kubernetes
pull: if-not-exists
load: none
node_selector:
  development: "yes"

steps:
  - name: submodules
    image: alpine/git
    environment:
      GIT_USER: { from_secret: GIT_USER }
      GIT_TOKEN: { from_secret: GIT_TOKEN }
    commands:
      - git config --global url."https://$GIT_USER:$GIT_TOKEN@git.i-sphere.ru".insteadOf "ssh://git@git.i-sphere.ru:30122"
      - git submodule update --init --recursive --remote --merge
    when:
      event:
        - push
      branch:
        - master

  - name: build-nginx
    image: plugins/kaniko
    depends_on:
      - submodules
    environment:
      container: kube
      PLUGIN_DOCKERFILE: Dockerfile-nginx
      PLUGIN_CONTEXT: .
      PLUGIN_CACHE_REPO: "${DRONE_REPO}-nginx"
      PLUGIN_ENABLE_CACHE: true
      PLUGIN_EXPAND_REPO: true
      PLUGIN_REGISTRY: { from_secret: GIT_HTTP_DOMAIN }
      PLUGIN_USERNAME: { from_secret: GIT_USER }
      PLUGIN_PASSWORD: { from_secret: GIT_TOKEN }
      PLUGIN_REPO: "${DRONE_REPO}-nginx"
      PLUGIN_TAGS: "${DRONE_COMMIT_BRANCH}"
    when:
      event:
        - push
      branch:
        - master

  - name: build-nodejs
    image: plugins/kaniko
    depends_on:
      - submodules
    environment:
      container: kube
      PLUGIN_DOCKERFILE: Dockerfile-nodejs
      PLUGIN_CONTEXT: .
      PLUGIN_CACHE_REPO: "${DRONE_REPO}-nodejs"
      PLUGIN_ENABLE_CACHE: true
      PLUGIN_EXPAND_REPO: true
      PLUGIN_REGISTRY: { from_secret: GIT_HTTP_DOMAIN }
      PLUGIN_USERNAME: { from_secret: GIT_USER }
      PLUGIN_PASSWORD: { from_secret: GIT_TOKEN }
      PLUGIN_REPO: "${DRONE_REPO}-nodejs"
      PLUGIN_TAGS: "${DRONE_COMMIT_BRANCH}"
    when:
      event:
        - push
      branch:
        - master

  - name: build
    image: plugins/kaniko
    depends_on:
      - submodules
    environment:
      container: kube
      PLUGIN_DOCKERFILE: Dockerfile
      PLUGIN_CONTEXT: .
      PLUGIN_CACHE_REPO: "${DRONE_REPO}"
      PLUGIN_ENABLE_CACHE: true
      PLUGIN_EXPAND_REPO: true
      PLUGIN_REGISTRY: { from_secret: GIT_HTTP_DOMAIN }
      PLUGIN_USERNAME: { from_secret: GIT_USER }
      PLUGIN_PASSWORD: { from_secret: GIT_TOKEN }
      PLUGIN_REPO: "${DRONE_REPO}"
      PLUGIN_TAGS: "${DRONE_COMMIT_BRANCH}"
    when:
      event:
        - push
      branch:
        - master

  - name: deploy
    image: alpine/k8s:1.24.13
    depends_on:
      - build
      - build-nginx
      - build-nodejs
    commands:
      - mkdir -p ~/.kube && printenv k8s_CONFIG | base64 -d > ~/.kube/config
      - sed -E -i -e "s/appVersion.*/appVersion:\ '${DRONE_COMMIT_SHA}-$(date +%s)'/g" .helm/Chart.yaml
      - echo "$(envsubst < .helm/Chart.yaml)" > .helm/Chart.yaml
      - echo "$(envsubst < .helm/values.yaml)" > .helm/values.yaml
      - helm upgrade
        -i main-service-${DRONE_COMMIT_BRANCH}
        -n main-service --create-namespace
        -f .helm/values.yaml
        .helm/
    environment:
      CI_REGISTRY_IMAGE: "gitea-http.gitea.svc.cluster.local/isphere-services/main-service-k8s"
      DOCKER: { from_secret: DOCKER }
      DOMAIN: { from_secret: DOMAIN }
      GIT_HTTP_DOMAIN: { from_secret: GIT_HTTP_DOMAIN }
      k8s_CONFIG: { from_secret: k8s_CONFIG }
    when:
      event:
        - push
      branch:
        - master

---
kind: secret
name: DOCKER
get: { path: settings-kube, name: DOCKER }

---
kind: secret
name: DOMAIN
get: { path: settings-kube, name: DOMAIN }

---
kind: secret
name: GIT_TOKEN
get: { path: settings-kube, name: GIT_TOKEN }

---
kind: secret
name: GIT_USER
get: { path: settings-kube, name: GIT_USER }

---
kind: secret
name: GIT_HTTP_DOMAIN
get: { path: settings-kube, name: GIT_HTTP_DOMAIN }

---
kind: secret
name: k8s_CONFIG
get: { path: settings-kube, name: k8s_CONFIG }


