{{- define "deployment.yaml" }}
{{- if .Daemon.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: daemons-master-{{ .Daemon.name }}
  labels:
    {{- include "chart.labels" .Root | nindent 4 }}
    app.kubernetes.io/component: daemons
  {{- with .Daemon.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Daemon.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: daemons-master-{{ .Daemon.name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: daemons
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        app.kubernetes.io/name: daemons-master-{{ .Daemon.name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        date: "{{ now | unixEpoch }}"
        app.kubernetes.io/component: daemons
    spec:
      {{- with .Daemon.initContainers }}
      initContainers:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: daemon
          image: "{{ .Daemon.image.repository }}:{{ .Daemon.image.tag }}"
          imagePullPolicy: {{ .Daemon.image.pullPolicy }}
          {{- with .Daemon.command }}
          command:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          envFrom:
            - configMapRef:
                name: {{ include "chart.name" . }}-configmap
            - secretRef:
                name: {{ include "chart.name" . }}-secrets
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          resources:
            {{- toYaml .Daemon.resources | nindent 12 }}
          {{- with .Daemon.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      serviceAccountName: {{ include "chart.serviceAccountName" . }}
      imagePullSecrets:
        - name: {{ include "chart.name" . }}-registry
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- with .Values.serviceAccount.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Daemon.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
{{- end }}
