apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart.name" . }}-secrets
  labels:
    {{- include "chart.labels" . | nindent 4 }}
data: { }
# DATABASE_LOGIN: ""
# DATABASE_PASSWORD: ""

# CAPTCHA_SERVICES_0_SECRET_KEY: ""
# CAPTCHA_SERVICES_1_SECRET_KEY: ""
# CAPTCHA_SERVICES_2_SECRET_KEY: ""
# CAPTCHA_SERVICES_3_SECRET_KEY: ""
# CAPTCHA_SERVICES_4_SECRET_KEY: ""
