apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chart.fullname" . }}-messenger-consume
  labels:
    {{- include "chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: consumer
spec:
  replicas: {{ .Values.messenger_consume.replicaCount }}
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "chart.name" . }}-messenger-consume
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        app.kubernetes.io/name: {{ include "chart.name" . }}-messenger-consume
        app.kubernetes.io/instance: {{ .Release.Name }}
        date: "{{ now | unixEpoch }}"
        app.kubernetes.io/component: consumer
    spec:
      containers:
        - name: messenger-consume
          image: "{{ .Values.messenger_consume.image.repository }}:{{ .Values.messenger_consume.image.tag }}"
          imagePullPolicy: {{ .Values.messenger_consume.image.pullPolicy }}
          command: [ 'bin/console', 'messenger:consume', '--exchange', 'isphere-go-modules-phones', '--queue', 'isphere-go-modules-phones' ]
          envFrom:
            - configMapRef:
                name: {{ include "chart.name" . }}-configmap-messenger-consume
          resources:
            {{- toYaml .Values.messenger_consume.resources | nindent 12 }}
      serviceAccountName: {{ include "chart.serviceAccountName" . }}
      imagePullSecrets:
        - name: {{ include "chart.name" . }}-registry
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- with .Values.serviceAccount.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
