kind: Deployment
#StatefulSet

replicaCount: 4

image:
  repository: ${GIT_HTTP_DOMAIN}/${CI_REPO}-server-${DRONE_COMMIT_BRANCH}
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the latest.
  tag: ${IMAGE_TAG}

command:
  - /bin/sh
args:
  - start.sh

resources: 
  limits: 
    cpu: 900m
    memory: 1Gi
  requests:
    cpu: 200m
    memory: 250Mi

StartupProbe:
  timeoutSeconds: 1
  periodSeconds: 1
  successThreshold: 1
  failureThreshold: 300
  httpGet:
    path: /status
    port: 80
    scheme: HTTP

livenessProbe:
  timeoutSeconds: 1
  periodSeconds: 10
  successThreshold: 1
  failureThreshold: 3
  httpGet:
    path: /
    port: 80
    scheme: HTTP


readinessProbe:
  timeoutSeconds: 1
  periodSeconds: 10
  successThreshold: 1
  failureThreshold: 2
  httpGet:
    path: /
    port: 80
    scheme: HTTP

affinity:
podAntiAffinity:
  requiredDuringSchedulingIgnoredDuringExecution:
  - labelSelector:
      matchExpressions:
      - key: app
        operator: In
        values:
        - ${DRONE_REPO_NAME}
    topologyKey: kubernetes.io/hostname


service:
  enabled: true
  type: LoadBalancer
  port: 80

imagePullSecrets:
- name: docker-registry
nameOverride: ""
fullnameOverride: ""

nodeSelector: {}

env:
- name: S3_BUCKET_MAIN
  value: ${S3_BUCKET_MAIN}
- name: S3_PREFIX_NNETWORKS
  value: ${S3_PREFIX_NNETWORKS}
- name: S3_PREFIX_IMAGES
  value: ${S3_PREFIX_IMAGES}
- name: S3_DEFAULT_REGION
  value: ${S3_DEFAULT_REGION}
- name: S3_ACCESS_KEY_ID
  value: ${S3_ACCESS_KEY_ID}
- name: S3_SECRET_ACCESS_KEY
  value: ${S3_SECRET_ACCESS_KEY}
- name: S3_URL_PATH
  value: ${S3_URL_PATH}
- name: CAPMONSTER_API_KEY
  value: ${CAPMONSTER_API_KEY}
- name: ANTICAPTCHA_API_KEY
  value: ${ANTICAPTCHA_API_KEY}
- name: RUCAPTCHA_API_KEY
  value: ${RUCAPTCHA_API_KEY}
- name: CAPMONSTER_LOCAL_URL
  value: ${CAPMONSTER_LOCAL_URL}
- name: POSTGRES_URL_ASYNC
  value: ${POSTGRES_URL_ASYNC}
- name: CALLBACK_URL
  value: ${CALLBACK_URL}
- name: SENTRY_URL_SERVER
  value: ${SENTRY_URL_SERVER}

envFrom:
- secretRef:
    name: settings-kube