{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name:  {{ .Release.Name  }}
  labels:
    {{- include "sources.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "sources.selectorLabels" . | nindent 4 }}
{{- end -}}