apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tor-proxy.fullname" . }}-ru
  labels:
    helm.sh/chart: {{ include "tor-proxy.chart" . }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{ include "tor-proxy.name" . }}-ru
    app.kubernetes.io/instance: {{ .Release.Name }}
    variant: ru
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.ru.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "tor-proxy.name" . }}-ru
      app.kubernetes.io/instance: {{ .Release.Name }}
      variant: ru
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        date: "{{ now | unixEpoch }}"
        helm.sh/chart: {{ include "tor-proxy.chart" . }}
        app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/name: {{ include "tor-proxy.name" . }}-ru
        app.kubernetes.io/instance: {{ .Release.Name }}
        variant: ru
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "tor-proxy.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            - name: NODE_NAME
              valueFrom: { fieldRef: { fieldPath: spec.nodeName } }
            - name: POD_NAME
              valueFrom: { fieldRef: { fieldPath: metadata.name } }
          command:
            - /app/build/tor-proxy
            - -entry-nodes=de,nl,se,ch,fi,no
            - -exit-nodes=ru
            - -exclude-nodes=cn,ir,sy,kp,cu,sa,eg,tr,id,ph,vn,th,my,sg,iq,pk,bd,qa,om,ae,kw,ye,ps,lb,jo,bh
            - -pool-size=5
            - -max-mem-in-queues-mb=16
          startupProbe:
            {{- toYaml .Values.startupProbe | nindent 12 }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
