---

- name: Install and Configure Zabbix Agent 2
  hosts: '{{ target }}'
  become: true

  vars_files:
    - ./vars/variables.yml

  tasks:

    - name: Install Zabbix Agent 2
      apt:
        name: zabbix-agent2
        state: present
        update_cache: yes

    - name: Configure Zabbix Agent 2
      template:
        src: "{{ template_zabbix_agent_path }}"
        dest: /etc/zabbix/zabbix_agent2.conf
        owner: root
        group: root
        mode: '0644'
      notify: restart zabbix-agent2

    - name: Start service zabbix-agent2
      service:
        name: zabbix-agent2
        state: started
        enabled: yes

  handlers:
    - name: restart zabbix-agent2
      systemd:
        name: zabbix-agent2
        state: restarted