kind: Deployment

replicaCount: 7

image:
  repository: ${GIT_HTTP_INTERNAL_DOMAIN}/${CI_REPO}-${DRONE_COMMIT_BRANCH}
  pullPolicy: IfNotPresent
  tag: ${IMAGE_TAG}

resources:
  limits:
    cpu: 40m
    memory: 100Mi
  requests:
    cpu: 25m
    memory: 30Mi

livenessProbe:
  exec:
    command:
      - /bin/sh
      - '-c'
      - healthtest 600
  initialDelaySeconds: 10
  timeoutSeconds: 5
  periodSeconds: 30
  successThreshold: 1
  failureThreshold: 3


topologySpreadConstraints:
  - maxSkew: 1
    topologyKey: topology.kubernetes.io/zone
    whenUnsatisfiable: ScheduleAnyway
    labelSelector:
      matchLabels:
        app: ${DRONE_REPO_NAME}

service:
  enabled: false


nodeSelector: {}

env:
- name: KEYDB_QUEUE
  value: ${KEYDB_QUEUE}
- name: SENTRY_URL
  value: ${SENTRY_URL}


envFrom:
- secretRef:
    name: settings-kube