imageCredentials:
  enabled: false
  registry: ""
  username: ""
  password: ""

nameOverride: "grabber-2-${DRONE_COMMIT_BRANCH}"
fullNameOverride: "grabber-2-${DRONE_COMMIT_BRANCH}"

DOCKER: "${DOCKER}"

service:
  type: ClusterIP
  port: 22

securityContext:
  capabilities:
    drop:
      - FOWNER
      - KILL
      - MKNOD
      - SETGID
      - SETUID

podAnnotations: {}

podSecurityContext: {}

nodeSelector: {}

tolerations: []

serviceAccount:
  create: true
  annotations: {}
  createRole: true
  affinity: {}

persistence:
  enabled: false

http_serve:
  replicaCount: 1

  service:
    port: 22

  image:
    repository: "${CI_REGISTRY_IMAGE}"
    pullPolicy: Always
    tag: "${DRONE_BRANCH}"

  resources:
    limits:
      cpu: 400m
      memory: 2Gi
    requests:
      cpu: 200m
      memory: 1Gi

  env: {}
