kind: Deployment 
#StatefulSet
#cronjob

ingress:
  enabled: false
#  annotations:
#    cert-manager.io/cluster-issuer: letsencrypt
#    certmanager.k8s.io/acme-challenge-type: http01
#    kubernetes.io/ingress.class: nginx
#  hosts:
#    - host: test.example.com
#      paths:
#        - /
#  tlsEnabled: true
#  tls:
#    - hosts:
#        - test.example.com
#      secretName   test.example.com

replicaCount: 0

schedule: "* * * * *"
 
image:
  repository: busybox
  pullPolicy: Always
  # Overrides the image tag whose default is the latest.
  tag: "latest"
 
 
service:
  enabled: true
  type: ClusterIP
  #loadBalancerIP: 
  port: 80

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

#command:
# - "/bin/sleep"
#arg:
# - "5000"
#nodeSelector: {}

#livenessProbe:
#  httpGet:
#    path: /
#    port: http

#readinessProbe:
#  httpGet:
#    path: /
#    port: http

tolerations: 
- effect: NoSchedule
  key: prod
  operator: Equal
  value: "yes"

topologySpreadConstraints:
  - maxSkew: 1
    topologyKey: topology.kubernetes.io/zone
    whenUnsatisfiable: ScheduleAnyway
    labelSelector:
      matchLabels:
        app: avito-web-api

#env:
#- name: ENV
#  value: test
#envFrom:
#- secretRef:
#    name: settings-kube
