apiVersion: v1
kind: Service
metadata:
  name: kafka-ui
  labels:
    app.kubernetes.io/name: kafka-ui
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

---
apiVersion: v1
kind: Endpoints
metadata:
  name: kafka-ui
  labels:
    app.kubernetes.io/name: kafka-ui
subsets:
  - addresses:
      - ip: 172.16.199.2
    ports:
      - port: 8080
