apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: gitea
  namespace: cnpg-system
spec:
  instances: 3
  primaryUpdateStrategy: unsupervised
  storage:
    storageClass: local-path
    size: 5Gi
    resizeInUseVolumes: True
