apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: wiki
  namespace: cnpg-system
spec:
  instances: 3
  primaryUpdateStrategy: unsupervised
  storage:
    storageClass: local-path
    size: 1Gi
    resizeInUseVolumes: True
    pvcTemplate:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
      storageClassName: local-path

