services:
  php-fpm:
    image: git.i-sphere.local/isphere-services/main-service-1:${CURRENT_BRANCH:-latest}
    build:
      dockerfile: .ci/docker/Dockerfile
      context: .
      x-bake:
        platforms:
          - linux/amd64
    env_file:
      - path: .env
