###########################
######## SERVICES #########
###########################

apiVersion: v1
kind: Service
metadata:
  name: jaeger-query
  labels:
    app: jaeger
    jaeger-infra: jaeger-service
spec:
  ports:
    - { name: query, port: 80, protocol: TCP, targetPort: query }

---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-collector
  labels:
    app: jaeger
    jaeger-infra: collector-service
spec:
  ports:
    - { name: otlp, port: 4318, targetPort: otlp }

---
############################
######## ENDPOINTS #########
############################

apiVersion: v1
kind: Endpoints
metadata:
  name: jaeger-query
  labels:
    app: jaeger
    jaeger-infra: jaeger-service
subsets:
  - addresses:
      - ip: 172.16.97.10
    ports:
      - { name: query, port: 16686 }

---
apiVersion: v1
kind: Endpoints
metadata:
  name: jaeger-collector
  labels:
    app: jaeger
    jaeger-infra: collector-service
subsets:
  - addresses:
      - ip: 172.16.97.10
    ports:
      - { name: otlp, port: 4318 }
