imageCredentials:
  enabled: false
  registry: ""
  username: ""
  password: ""

nameOverride: "${DRONE_REPO_NAME}-${DRONE_COMMIT_BRANCH}"
fullNameOverride: "${DRONE_REPO_NAME}-${DRONE_COMMIT_BRANCH}"

DOCKER: "${DOCKER}"

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  tlsEnabled: false

securityContext:
  capabilities:
    drop:
      - FOWNER
      - KILL
      - MKNOD
      - SETGID
      - SETUID

podAnnotations: {}

podSecurityContext: {}

nodeSelector: {}

tolerations: []

serviceAccount:
  create: true
  annotations: {}
  createRole: true
  affinity: {}

persistence:
  enabled: true
  existingClaim: false
  accessMode: ReadWriteMany
  size: 10Gi
  storageClass: ceph-filesystem

app:
  replicaCount: 1

  service:
    port: 80

  image:
    repository: "${CI_REGISTRY_IMAGE}"
    pullPolicy: Always
    tag: "${DRONE_BRANCH}"

  resources:
    limits:
      cpu: 500m
      memory: 256Mi
    requests:
      cpu: 200m
      memory: 128Mi

  env:
    TELEGRAM_BOT_TOKEN: "${TELEGRAM_BOT_TOKEN}"
    TELEGRAM_CHAT_ID: "${TELEGRAM_CHAT_ID}"
    SENTRY_DSN: "${SENTRY_DSN}"
