framework:
  cache:
    app: cache.adapter.memcached
    default_memcached_provider: '%env(MEMCACHED_DSN)%'
    system: cache.adapter.memcached
    pools:
      doctrine.result_cache_pool:
        adapter: cache.app

  secret: '%env(APP_SECRET)%'
  http_method_override: false
  http_cache: true

  session:
    handler_id: null
    cookie_secure: auto
    cookie_samesite: lax
    storage_factory_id: session.storage.factory.native

  php_errors:
    log: true

  serializer:
    name_converter: serializer.name_converter.camel_case_to_snake_case

  trusted_proxies: '127.0.0.1,REMOTE_ADDR'
  trusted_headers:
    - 'x-forwarded-for'
    - 'x-forwarded-host'
    - 'x-forwarded-port'
    - 'x-forwarded-prefix'
    - 'x-forwarded-proto'

when@test:
  framework:
    test: true
    session:
      storage_factory_id: session.storage.factory.mock_file
