apiVersion: v1
kind: Service
metadata:
  name: clickhouse
  namespace: {{.Release.Namespace}}
  labels:
    app.kubernetes.io/name: clickhouse
  annotations:
    helm.sh/hook: post-install,post-upgrade
spec:
  ports:
    - name: tcp
      protocol: TCP
      port: 8123
      targetPort: tcp
    - name: metrics
      protocol: TCP
      port: 9363
      targetPort: metrics

---
apiVersion: v1
kind: Endpoints
metadata:
  name: clickhouse
  namespace: {{.Release.Namespace}}
  labels:
    app.kubernetes.io/name: clickhouse
  annotations:
    helm.sh/hook: post-install,post-upgrade
subsets:
  - addresses:
      - ip: 172.16.199.1
    ports:
      - name: tcp
        port: 8123
      - name: metrics
        port: 9363
