imageCredentials:
  enabled: false
  registry: ""
  username: ""
  password: ""

nameOverride: "${DRONE_REPO_NAME}-${DRONE_COMMIT_BRANCH}"
fullNameOverride: "${DRONE_REPO_NAME}-${DRONE_COMMIT_BRANCH}"

DOCKER: "${DOCKER}"

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  tlsEnabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    certmanager.k8s.io/acme-challenge-type: http01
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: "account.git.i-sphere.ru"
      paths:
        - /
  tls:
    - secretName: "account.git.i-sphere.ru"
      hosts:
        - "account.git.i-sphere.ru"

securityContext:
  capabilities:
    drop:
      - FOWNER
      - KILL
      - MKNOD
      - SETGID
      - SETUID

podAnnotations: { }

podSecurityContext: { }

nodeSelector: { }

tolerations: [ ]

serviceAccount:
  create: true
  annotations: { }
  createRole: true
  affinity: { }

app:
  replicaCount: 1

  service:
    port: 80

  image:
    repository: "${CI_REGISTRY_IMAGE}"
    pullPolicy: Always
    tag: "${DRONE_BRANCH}"

  resources:
    limits:
      cpu: 500m
      memory: 256Mi
    requests:
      cpu: 200m
      memory: 128Mi

  env:
    APP_ENV: "dev"
    EXAMPLE_CLIENT_ID: "34d01c4c-bace-498d-be9b-d3fab9d0c098"
    EXAMPLE_CLIENT_SECRET: "eOc8Id7roBjDu.lL.Di3cr86no"
    HYDRA_ADMIN_DEBUG: "true"
    HYDRA_ADMIN_URL: "http://hydra-admin.ory:4445"
    HYDRA_PUBLIC_ENDPOINT: "https://oauth2.git.i-sphere.ru"
    HYDRA_PUBLIC_URL: "http://hydra-public.ory:4444"
    KRATOS_ADMIN_DEBUG: "true"
    KRATOS_ADMIN_URL: "http://kratos-admin.ory"
    KRATOS_PUBLIC_DEBUG: "true"
    KRATOS_PUBLIC_ENDPOINT: "https://auth.git.i-sphere.ru"
    KRATOS_PUBLIC_URL: "http://kratos-public.ory"
    OATHKEEPER_API_DEBUG: "true"
    OATHKEEPER_API_URL: "http://oathkeeper-api.ory:4456"
    OATHKEEPER_PROXY_URL: "http://oathkeeper-proxy.ory:4455"

