---

- name: Install packages
  hosts: '{{ target }}'
  gather_facts: false
  become: true

  tasks:

  - name: Update apt package cache
    apt:
      update_cache: true
      
  - name: Install package
    apt:
      name: 
        - package_name
      state: present